org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.19.2
minecraft_version_range=[1.19.2,1.20)
forge_version=43.4.20
forge_version_range=[43,)
loader_version_range=[43,)
mapping_channel=official
mapping_version=1.19.2

## Mod Properties
mod_id=flintaxedt
mod_name=Flimsy Flint Axe (DT)
mod_license=MIT
mod_version=1.0.0
mod_group_id=phen0n
mod_authors=Phen0n
mod_description=Flint can be used as an axe on Dynamic Trees, but it's fragile.
